package Vista;

import javax.swing.*;

public class fmrAgregarAlumnos extends JDialog {
    private JPanel contentPane;
    private JTabbedPane tabbedPane1;
    private JTextField txtNombres;
    private JTextField txtEmail;
    private JTextField txtApellidos;
    private JTextField txtEdad;
    private JTextField txtFechaNacimiento;
    private JTextField txtCiudad;
    private JTextField txtTelefono;
    private JTextField txtNacionalidad;
    private JTextField txtFechaMatricula;
    private JTextField txtDireccion;
    private JTextField txtCurso;
    private JTextField txtLetra;
    private JTextField txtElectivo;
    private JTextField txtEnfermedades;
    private JTextField txtDatosAdicionales;
    private JRadioButton rdoMasculino;
    private JRadioButton rdoFemenino;
    private JRadioButton rdoOtro;
    private JTextField txtRut;
    private JButton btnBuscar;
    private JLabel lblRut;
    private JLabel lblNombres;
    private JLabel lblApellidos;
    private JLabel lblEdad;
    private JLabel lblFechaNacimiento;
    private JLabel lblEmail;
    private JLabel lblCiudad;
    private JLabel lblTelefono;
    private JLabel lblNacionalidad;
    private JLabel lblFechaMatricula;
    private JLabel lblDireccion;
    private JLabel lblCurso;
    private JLabel lblLetra;
    private JLabel lblElectivo;
    private JLabel lblEnfermedades;
    private JLabel lblDatosAdicionales;
    private JLabel lblGenero;
    private JTable tblListado;
    private JButton btnGrabar;
    private JButton btnLimpiar;
    private JButton btnBorrar;
    private JButton btnListar;
    private JButton btnModificar;
    private JButton btnSalir;
    private JLabel lblAgregarAlumno;
    private JTextField textField1;
    private JTextField textField2;
    private JTextField textField3;
    private JTextField textField4;
    private JTextField textField5;
    private JTextField textField6;
    private JTextField textField7;
    private JTextField textField8;
    private JRadioButton rdoMasculinoApoderado;
    private JRadioButton rdoFemeninoApoderado;
    private JRadioButton rdoOtroApoderado;
    private JLabel lblAgregarApoderado;
    private JButton btnLimpiarApoderado;
    private JLabel lblRutApoderado;
    private JLabel lblDIreccionApoderado;
    private JLabel lblObservaciones;
    private JLabel lblNombresApoderado;
    private JLabel lblApellidosApoderado;
    private JLabel lblCiudadApoderado;
    private JLabel lblGeneroApoderado;
    private JLabel lblParentescoApoderado;
    private JButton buttonOK;

    public fmrAgregarAlumnos() {
        setContentPane(contentPane);
        setModal(true);
        getRootPane().setDefaultButton(buttonOK);
    }
}
